name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Kod klonla
        uses: actions/checkout@v3

      - name: PHP quraşdır
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Composer install
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Env faylı köçür
        run: cp .env.example .env

      - name: Laravel key yarad
        run: php artisan key:generate

      - name: Laravel test et (əgər varsa)
        run: php artisan test

      - name: Deploy et (serverə yüklə)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: 22
          source: "."
          target: "/var/www/project1"
